const {test}=require('node:test');const assert=require('node:assert/strict');
const ui=require('../custom_vision/static/calibration_capture_ui.js');
const dashboard=require('../custom_vision/static/calibration_dashboard.js');
function timers(){let id=0;const pending=new Map();return {pending,setTimer(fn,delay){pending.set(++id,{fn,delay});return id;},clearTimer:n=>pending.delete(n),fire(){const [n,item]=pending.entries().next().value;pending.delete(n);return item.fn();}};}
const status=(id='capture-a',frame=1)=>({capture_id:id,session_id:'session-a',state:'running',board:{cols:7,rows:5,square_size_m:.03},snapshot_eligible:true,frame:{frame_id:frame,width:640,height:480,corners_px:Array.from({length:35},(_,i)=>[10+i*3,20+i*2]),corner_count:35}});

test('measured board configuration rejects absent or invalid spacing and corner counts',()=>{assert.equal(ui.validBoard({cols:7,rows:5,square_size_m:.03}),true);for(const change of [{cols:2},{rows:41},{square_size_m:0},{square_size_m:NaN},{square_size_m:'0.03'}])assert.equal(ui.validBoard({...status().board,...change}),false);assert.notEqual(ui.boardSignature(status().board),ui.boardSignature({...status().board,square_size_m:.04}));});
test('capture declarations explicitly select source without uploading or inventing timestamp assets',()=>{const values={cols:'7',rows:'5',square_size_m:'.03',user_label:'Synthetic board',input_kind:'capture',source_id:'synthetic:chessboard',focus_kind:'unknown',max_views:180,interval_s:.7,novelty:.025,max_sharpness_px:3,min_contrast:40};const spec=dashboard.normalizeSpec(values,[],'unrelated-sidecar');assert.deepEqual(spec.input,{kind:'capture',source_id:'synthetic:chessboard',asset_ids:[],timestamps_asset_id:null});assert.throws(()=>dashboard.normalizeSpec({...values,source_id:''},[]),/selected source/);assert.throws(()=>dashboard.normalizeSpec(values,['unrelated-image']),/Import/);});
test('actual overlays discard nonfinite, out-of-image or malformed detector corners',()=>{assert.deepEqual(ui.safeCorners({width:640,height:480,corners_px:[[10,20],[-1,0],[640,2],[2,480],[NaN,1],['2',1],[1,2,3]]}),[[10,20]]);assert.deepEqual(ui.safeCorners({width:null,height:480,corners_px:[[1,2]]}),[]);});
test('timing never upgrades host-read fallback or unverified hardware metadata to exposure midpoint',()=>{assert.match(ui.timingLabel({timestamp_source:'host_frame_read_complete',exposure_duration_ms:2}),/fallback/);assert.match(ui.timingLabel({timestamp_source:'hardware_exposure_midpoint',clock_mapping_validated:false}),/unavailable/);assert.match(ui.timingLabel({timestamp_source:'hardware_exposure_midpoint',clock_mapping_validated:true,exposure_duration_ms:0,rolling_shutter:true}),/0.000 ms exposure/);assert.match(ui.timingLabel({timestamp_source:'synthetic'}),/No physical/);assert.match(ui.timingLabel(null),/unavailable/);});
test('no source is opened by controller construction and snapshot always names exact capture frame',async()=>{const clock=timers(),calls=[];const c=ui.createController({...clock,request:async(path,data)=>{calls.push([path,data]);return path.endsWith('/start')?status():{saved:true};}});assert.equal(calls.length,0);await assert.rejects(c.start('session-a',''),/Explicitly/);await c.start('session-a','synthetic:chessboard');await c.snapshot();assert.deepEqual(calls[1],['/api/calibration/capture/snapshot',{capture_id:'capture-a',frame_id:1}]);await assert.rejects(c.snapshot(),/stale/);await c.stop();assert.equal(clock.pending.size,0);});
test('repeated snapshot clicks coalesce and interrupted saves stay isolated from changed session',async()=>{const clock=timers();let save;const c=ui.createController({...clock,request:async(path)=>path.endsWith('/start')?status():path.endsWith('/snapshot')?new Promise(r=>save=r):{}});await c.start('session-a','explicit');const pending=c.snapshot();await assert.rejects(c.snapshot(),/already/);await c.stop('Board changed; old session retained.');save({saved:true});await assert.rejects(pending,/original session/);assert.equal(c.isSnapshotPending(),false);});
test('late status from old capture cannot restore snapshot eligibility after stop',async()=>{const clock=timers(),updates=[];let reply;const c=ui.createController({...clock,request:async path=>path.endsWith('/start')?status():path.endsWith('/status')?new Promise(r=>reply=r):{},onStatus:s=>updates.push(s.state)});await c.start('session-a','explicit');const pending=clock.fire();await c.stop();reply(status());await pending;assert.deepEqual(updates,['running','stopped']);assert.equal(c.current().snapshot_eligible,false);assert.equal(clock.pending.size,0);});
test('offline preview suppresses snapshots and keeps bounded reconnect polling with explicit release',async()=>{const clock=timers(),errors=[];let fail=true;const c=ui.createController({...clock,request:async path=>{if(path.endsWith('/start'))return status();if(path.endsWith('/status')){if(fail)throw new Error('connection lost');return status();}return {};},onError:e=>errors.push(e.message)});await c.start('session-a','explicit');await clock.fire();assert.equal(c.current().state,'offline');assert.equal(c.current().snapshot_eligible,false);assert.equal(clock.pending.size,1);await assert.rejects(c.start('session-b','explicit'),/Stop/);fail=false;await clock.fire();assert.equal(c.current().state,'running');assert.deepEqual(errors,['connection lost']);await c.stop();});
test('late start after invalidation releases only the explicitly opened capture',async()=>{const clock=timers(),calls=[];let reply;const c=ui.createController({...clock,request:async(path,data)=>{calls.push([path,data]);return path.endsWith('/start')?new Promise(r=>reply=r):{};}});const starting=c.start('session-a','explicit');await c.stop('config changed');reply(status());assert.equal(await starting,null);assert.deepEqual(calls.at(-1),['/api/calibration/capture/stop',{capture_id:'capture-a'}]);assert.equal(clock.pending.size,0);});
test('mismatched capture status cannot be reused as a measurement from this session',()=>{assert.equal(ui.normalizeStatus(status('other'),'capture-a'),null);assert.equal(ui.normalizeStatus({...status(),state:'stopped'}).snapshot_eligible,false);});

test('ordinary chessboards require every expected inner corner; partial views cannot be captured',()=>{const full=ui.normalizeStatus({...status(),state:'preview'});assert.equal(full.snapshot_eligible,true);const partial=ui.normalizeStatus({...status(),frame:{...status().frame,corners_px:[[10,20]],corner_count:1}});assert.equal(partial.snapshot_eligible,false);});

test('millimeter UI spacing round-trips exactly to the meter session contract',()=>{assert.equal(dashboard.millimetersToMeters('30'),.03);assert.equal(dashboard.metersToMillimeters(.03),30);assert.equal(dashboard.millimetersToMeters('24.375'),.024375);assert.equal(dashboard.metersToMillimeters(.024375),24.375);assert.equal(dashboard.millimetersToMeters(''),null);assert.equal(dashboard.metersToMillimeters(null),null);assert.throws(()=>dashboard.millimetersToMeters('not measured'),/millimeters/);});
function captureValues(){return {cols:'7',rows:'5',square_size_m:.03,user_label:'Explicit source',physical_id:'',width:'',height:'',focus_kind:'unknown',focus_value:'',focus_locked:false,max_views:180,interval_s:.7,novelty:.025,max_sharpness_px:3,min_contrast:40};}
test('explicit source identity and exact mode populate unspecified capture declarations',()=>{const source={source_id:'configured-camera',label:'Configured camera',camera:{physical_id:'serial-1'},mode:{width:640,height:480,crop:{x:0,y:0,width:640,height:480},binning:[1,1],focus:{kind:'fixed',value:null,locked:true}}};const spec=dashboard.captureSpecification(captureValues(),source);assert.equal(spec.camera.physical_id,'serial-1');assert.deepEqual(spec.mode,source.mode);assert.deepEqual(spec.board,{cols:7,rows:5,square_size_m:.03});assert.equal(spec.input.source_id,'configured-camera');for(const change of [{physical_id:'wrong-serial'},{width:'1280',height:'800'},{crop_x:'1',crop_y:'0',crop_width:'640',crop_height:'480'},{binning_x:'2',binning_y:'2'},{focus_kind:'manual',focus_value:'5',focus_locked:true}])assert.throws(()=>dashboard.captureSpecification({...captureValues(),...change},source),/conflict/);});
test('synthetic source retains its known null identity and unknown focus instead of inventing physical metadata',()=>{const source={source_id:'synthetic',label:'Synthetic',camera:{physical_id:null},mode:{width:640,height:480,crop:null,binning:null,focus:{kind:'unknown',value:null,locked:false}}};const spec=dashboard.captureSpecification(captureValues(),source);assert.equal(spec.camera.physical_id,null);assert.deepEqual(spec.mode,source.mode);assert.throws(()=>dashboard.captureSpecification({...captureValues(),physical_id:'physical-camera'},source),/conflict/);});

test('guided native defaults require 40 views and spline evidence while offline preferences remain unchanged',()=>{const offline={solver:'opencv',min_views:17,no_spline:true};assert.deepEqual(dashboard.solverPreferencesForSession('capture',offline),{solver:'mrcal',min_views:40,no_spline:false});assert.deepEqual(dashboard.solverPreferencesForSession('images',offline),offline);assert.deepEqual(offline,{solver:'opencv',min_views:17,no_spline:true});});
test('captured snapshots are already selected and never expose a rejected selection action',()=>{assert.deepEqual(dashboard.selectionPresentation('capture',true),{show_selection:false,capture_note:'Saved snapshots are already selected. Stop preview, then review these observations.'});assert.equal(dashboard.selectionPresentation('capture',false).show_selection,false);assert.match(dashboard.selectionPresentation('capture',false).capture_note,/Review/);assert.equal(dashboard.selectionPresentation('video',false).show_selection,true);});

test('an explicit OpenCV capture solve remains available without silently falling back from unavailable mrcal',()=>{const session={input:{kind:'capture'},status:'selected',summary:{accepted_views:40}},solvers={opencv:{available:true},mrcal:{available:false}};assert.equal(dashboard.canSolveSession({session,solver:'opencv',solvers,reviewed:true}),true);assert.equal(dashboard.canSolveSession({session,solver:'mrcal',solvers,reviewed:true}),false);assert.equal(dashboard.canSolveSession({session,solver:'opencv',solvers,reviewed:false}),false);assert.equal(dashboard.canSolveSession({session,solver:'opencv',solvers,reviewed:true,capturing:true}),false);});

test('opening a saved session preserves the selected identity across stop-driven session refresh',async()=>{let selector='native-session',loaded=[];const selected=selector;const session=await dashboard.openSessionAfterStop(selected,async()=>{selector='previous-capture';},async id=>{loaded.push(id);return {session_id:id};});assert.equal(selector,'previous-capture');assert.deepEqual(loaded,['native-session']);assert.equal(session.session_id,'native-session');await assert.rejects(dashboard.openSessionAfterStop('',async()=>{},async()=>{}),/Choose/);});
